# pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [3]:
np.array([2, 3, 4, 5])

array([2, 3, 4, 5])

In [4]:
np.array([2, 3, 4, 5, 321.0321])

array([  2.    ,   3.    ,   4.    ,   5.    , 321.0321])

In [5]:
np.array([2, 3, 4, 5, 321.0321, True, False])

array([  2.    ,   3.    ,   4.    ,   5.    , 321.0321,   1.    ,
         0.    ])

In [6]:
np.array([2, 3, 4, 5,True, False])

array([2, 3, 4, 5, 1, 0])

In [8]:
np.array([2, 3, 4, 5, 321.0321, True, False, "hello"])

array(['2', '3', '4', '5', '321.0321', 'True', 'False', 'hello'],
      dtype='<U32')

In [9]:
np.array([2, 3, 4, 5, 321.0321, True, False, "hello", [321,3, 12]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (9,) + inhomogeneous part.

In [12]:
array = np.array([[2, 3, 4,], [321,3, 12]])
array 

array([[  2,   3,   4],
       [321,   3,  12]])

In [13]:
array.dtype, array.shape

(dtype('int64'), (2, 3))

In [14]:
array.reshape((6,))

array([  2,   3,   4, 321,   3,  12])

In [15]:
array.flatten()

array([  2,   3,   4, 321,   3,  12])

In [16]:
array.reshape((3, 2))

array([[  2,   3],
       [  4, 321],
       [  3,  12]])

In [19]:
array.reshape((2, 3, 1))

array([[[  2],
        [  3],
        [  4]],

       [[321],
        [  3],
        [ 12]]])

In [20]:
array.reshape((2, 3, 1, 1))

array([[[[  2]],

        [[  3]],

        [[  4]]],


       [[[321]],

        [[  3]],

        [[ 12]]]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10, dtype=np.int8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [25]:
np.arange(10, dtype=np.uint8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [26]:
bin(2)

'0b10'

In [28]:
for i in range(17):
    print("i=", i, "in binar:", bin(i)[2:])

i= 0 in binar: 0
i= 1 in binar: 1
i= 2 in binar: 10
i= 3 in binar: 11
i= 4 in binar: 100
i= 5 in binar: 101
i= 6 in binar: 110
i= 7 in binar: 111
i= 8 in binar: 1000
i= 9 in binar: 1001
i= 10 in binar: 1010
i= 11 in binar: 1011
i= 12 in binar: 1100
i= 13 in binar: 1101
i= 14 in binar: 1110
i= 15 in binar: 1111
i= 16 in binar: 10000


In [29]:
bin(2 ** 8)

'0b100000000'

In [30]:
bin(2 ** 8 - 1)

'0b11111111'

# Uint8 -> 0..255

In [31]:
np.array([2 ** 8 - 1,], dtype=np.uint8)

array([255], dtype=uint8)

In [32]:
np.array([2 ** 8 - 1, 2 ** 8], dtype=np.uint8)

OverflowError: Python integer 256 out of bounds for uint8

# Int8 -> -128..127

In [34]:
np.array([-128, 127], dtype=np.int8)

array([-128,  127], dtype=int8)

In [35]:
np.array([-129, 127], dtype=np.int8)

OverflowError: Python integer -129 out of bounds for int8

In [36]:
np.array([-128, 128], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

# Operatii matematice

In [38]:
np.random.randint(1, 100, size=7)

array([49, 85,  6,  1, 13, 29, 74])

In [39]:
array = np.random.randint(1, 100, size=7)
array

array([14, 55, 48, 50, 63, 30, 43])

In [40]:
array - 10

array([ 4, 45, 38, 40, 53, 20, 33])

In [41]:
array * 2

array([ 28, 110,  96, 100, 126,  60,  86])

In [42]:
array2 = np.random.randint(1, 100, size=7)
array2

array([45, 20, 92, 87, 82, 32, 88])

In [43]:
array1 = np.random.randint(1, 100, size=7)
array1

array([74, 75, 23, 29, 50, 72, 64])

In [44]:
array2 - array1

array([-29, -55,  69,  58,  32, -40,  24])

In [45]:
array2

array([45, 20, 92, 87, 82, 32, 88])

In [46]:
array2.min()

np.int64(20)

In [47]:
min(array2)

np.int64(20)

In [48]:
array2.argmin()

np.int64(1)

# Operatii logice

In [49]:
array

array([14, 55, 48, 50, 63, 30, 43])

In [50]:
array > 50

array([False,  True, False, False,  True, False, False])

In [51]:
array [array > 50]

array([55, 63])

In [ ]:
array = np.array([14, 55, 48, 50, 63, 30, 43])

conditie = array > 50
array [conditie]

array([55, 63])

In [61]:
array = np.array([14, 55, 48, 50, 63, 30, 43])

conditie1 = array > 50
conditie2 = array < 60
array [conditie1 & conditie2]

array([55])

In [56]:
array = np.array(['button1', 'autton2', 'button3'])
array

array(['button1', 'autton2', 'button3'], dtype='<U7')

In [57]:
sorted(array)

[np.str_('autton2'), np.str_('button1'), np.str_('button3')]